user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

movies:
    resource: "@MoviesBundle/Controller/"
    type:     annotation
    prefix:   /

api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

