<?php

namespace MoviesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GenreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenreRepository extends EntityRepository
{
//    public function getAllGenresForUser($user)
//    {
//        return $this->getEntityManager()
//            ->createQueryBuilder('g')
//            ->join('g.movies', 'm')
//            ->join('m.users', 'u')
//            ->where('u.id = :userId')->setParameter('userId', $user->getId())
//            ->orderBy('g.type', 'ASC')
//            ->getQuery()
//            ->getResult();
//    }
}
