<?php

namespace MoviesBundle\Entity;

/**
 * MovieUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieUserRepository extends \Doctrine\ORM\EntityRepository
{
}
