<?php

namespace MoviesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MovieCastRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieCastRepository extends EntityRepository
{
}
